spring:
  activemq:
    broker-url: 
  application:
    name: hello-eureka-server
    
eureka:
  client:
    allow-redirects: false
    register-with-eureka: true
    fetch-registry: true
  service-url:
     default-zone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
      