spring:
  application:
    name: hello-eureka-service
    
 # Configure this Discovery Server
eureka:
  client: 
    allow-redirects: false
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8070
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10 
# HTTP (Tomcat) port

logging:
 level:
  com:
   netflix:
    eureka: OFF
    discovery: OFF
